steps:
  # Clone source code from Github
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/rfahmi/elsa.git", "."]

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/elsa-ai/elsa", "."]

  # Push the container image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/elsa-ai/elsa"]

  # Deploy the container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "elsa"
      - "--image=gcr.io/elsa-ai/elsa"
      - "--region=asia-southeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
images:
  - "gcr.io/elsa-ai/elsa"
